### ISSUE TITLE
本地预览报错

### ISSUE THREAD

**Issue by emyia2001** [hexWars/hexw#2]
17:51:10 watching for file changes...
17:51:12 [200] / 12ms
17:51:13 [ERROR] [vite] Internal server error: Transform failed with 1 error:
E:/astro/hexw/src/layouts/RootLayout.astro?astro&amp;type=script&amp;index=0&amp;lang.ts:2:7: ERROR: Expected "(" but found "{"
  Plugin: vite:esbuild
  File: E:/astro/hexw/src/layouts/RootLayout.astro?astro&amp;type=script&amp;index=0&amp;lang.ts:2:7
  
  Expected "(" but found "{"
  1  |  ---
  2  |  import { LOCALE } from "@/config";
     |         ^
  3  |  import { ViewTransitions } from "astro:transitions";
  4  |  interface Props {
  
      at failureErrorWithLog (E:\astro\hexw\node_modules\vite\node_modules\esbuild\lib\main.js:1651:15)
      at E:\astro\hexw\node_modules\vite\node_modules\esbuild\lib\main.js:849:29
      at responseCallbacks.<computed> (E:\astro\hexw\node_modules\vite\node_modules\esbuild\lib\main.js:704:9)
      at handleIncomingPacket (E:\astro\hexw\node_modules\vite\node_modules\esbuild\lib\main.js:764:9)
      at Socket.readFromStdout (E:\astro\hexw\node_modules\vite\node_modules\esbuild\lib\main.js:680:7)
      at Socket.emit (node:events:519:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5)
      at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
      at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)
17:51:13 [ERROR] [vite] Internal server error: [postcss] E:/astro/hexw/node_modules/astro/components/ViewTransitions.astro?astro&amp;type=sty
le&amp;index=0&amp;lang.css:1:1: Unknown word
  Plugin: vite:css
  File: E:/astro/hexw/node_modules/astro/components/ViewTransitions.astro?astro&amp;type=style&amp;index=0&amp;lang.css:1:0
  1  |  ---
     |  ^
  2  |  type Fallback = 'none' | 'animate' | 'swap';
  3  |  
      at Input.error (E:\astro\hexw\node_modules\postcss\lib\input.js:106:16)
      at Parser.unknownWord (E:\astro\hexw\node_modules\postcss\lib\parser.js:593:22)
      at Parser.other (E:\astro\hexw\node_modules\postcss\lib\parser.js:435:12)
      at Parser.parse (E:\astro\hexw\node_modules\postcss\lib\parser.js:470:16)
      at parse (E:\astro\hexw\node_modules\postcss\lib\parse.js:11:12)
      at new LazyResult (E:\astro\hexw\node_modules\postcss\lib\lazy-result.js:133:16)
      at Processor.process (E:\astro\hexw\node_modules\postcss\lib\processor.js:53:14)
      at compileCSS (file:///E:/astro/hexw/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:32272:63)
      at async TransformContext.transform (file:///E:/astro/hexw/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:31583:56)
      at async Object.transform (file:///E:/astro/hexw/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:51139:30)
      at async loadAndTransform (file:///E:/astro/hexw/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:53894:29)
17:51:13 [ERROR] [vite] Internal server error: Transform failed with 1 error:
E:/astro/hexw/src/layouts/RootLayout.astro?astro&amp;type=script&amp;index=1&amp;lang.ts:2:7: ERROR: Expected "(" but found "{"
  Plugin: vite:esbuild
  File: E:/astro/hexw/src/layouts/RootLayout.astro?astro&amp;type=script&amp;index=1&amp;lang.ts:2:7
  
  Expected "(" but found "{"
  1  |  ---
  2  |  import { LOCALE } from "@/config";
     |         ^
  3  |  import { ViewTransitions } from "astro:transitions";
  4  |  interface Props {
  
      at failureErrorWithLog (E:\astro\hexw\node_modules\vite\node_modules\esbuild\lib\main.js:1651:15)
      at E:\astro\hexw\node_modules\vite\node_modules\esbuild\lib\main.js:849:29
      at responseCallbacks.<computed> (E:\astro\hexw\node_modules\vite\node_modules\esbuild\lib\main.js:704:9)
      at handleIncomingPacket (E:\astro\hexw\node_modules\vite\node_modules\esbuild\lib\main.js:764:9)
      at Socket.readFromStdout (E:\astro\hexw\node_modules\vite\node_modules\esbuild\lib\main.js:680:7)
      at Socket.emit (node:events:519:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5)
      at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
      at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)
17:51:13 [ERROR] [vite] Internal server error: Transform failed with 1 error:
E:/astro/hexw/node_modules/astro/components/ViewTransitions.astro?v=906590c6&astro&amp;type=script&amp;index=0&amp;lang.ts:2:5: ERROR: Expect
ed ";" but found "Fallback"
  Plugin: vite:esbuild
  File: E:/astro/hexw/node_modules/astro/components/ViewTransitions.astro?v=906590c6&astro&amp;type=script&amp;index=0&amp;lang.ts:2:5
  
  Expected ";" but found "Fallback"
  1  |  ---
  2  |  type Fallback = 'none' | 'animate' | 'swap';
     |       ^
  3  |  
  4  |  export interface Props {
  
      at failureErrorWithLog (E:\astro\hexw\node_modules\vite\node_modules\esbuild\lib\main.js:1651:15)
      at E:\astro\hexw\node_modules\vite\node_modules\esbuild\lib\main.js:849:29
      at responseCallbacks.<computed> (E:\astro\hexw\node_modules\vite\node_modules\esbuild\lib\main.js:704:9)
      at handleIncomingPacket (E:\astro\hexw\node_modules\vite\node_modules\esbuild\lib\main.js:764:9)
      at Socket.readFromStdout (E:\astro\hexw\node_modules\vite\node_modules\esbuild\lib\main.js:680:7)
      at Socket.emit (node:events:519:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5)
      at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
      at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)
17:51:13 [ERROR] [vite] Internal server error: [postcss] E:/astro/hexw/src/components/Moving.astro?astro&amp;type=style&amp;index=0&amp;lang.
css:5:1: Unknown word
  Plugin: vite:css
  File: E:/astro/hexw/src/components/Moving.astro?astro&amp;type=style&amp;index=0&amp;lang.css:5:0
  3  |  ---
  4  |  
  5  |  <div
     |  ^
  6  |      id="movingCircle"
  7  |      class="w-44 h-44 pointer-events-none rounded-full bg-ring/50 z-100 blur-3xl fixed"
      at Input.error (E:\astro\hexw\node_modules\postcss\lib\input.js:106:16)
      at Parser.unknownWord (E:\astro\hexw\node_modules\postcss\lib\parser.js:593:22)
      at Parser.decl (E:\astro\hexw\node_modules\postcss\lib\parser.js:236:16)
      at Parser.other (E:\astro\hexw\node_modules\postcss\lib\parser.js:399:18)
      at Parser.parse (E:\astro\hexw\node_modules\postcss\lib\parser.js:470:16)
      at parse (E:\astro\hexw\node_modules\postcss\lib\parse.js:11:12)
      at new LazyResult (E:\astro\hexw\node_modules\postcss\lib\lazy-result.js:133:16)
      at Processor.process (E:\astro\hexw\node_modules\postcss\lib\processor.js:53:14)
      at compileCSS (file:///E:/astro/hexw/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:32272:63)
      at async TransformContext.transform (file:///E:/astro/hexw/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:31583:56)
      at async Object.transform (file:///E:/astro/hexw/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:51139:30)
      at async loadAndTransform (file:///E:/astro/hexw/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:53894:29)
17:51:13 [ERROR] [vite] Internal server error: [postcss] E:/astro/hexw/src/pages/index.astro?astro&amp;type=style&amp;index=0&amp;lang.css:1:
1: Unknown word
  Plugin: vite:css
  File: E:/astro/hexw/src/pages/index.astro?astro&amp;type=style&amp;index=0&amp;lang.css:1:0
  1  |  ---
     |  ^
  2  |  import RootLayout from "@/layouts/RootLayout.astro";
  3  |  import { SocialIcons } from "@/components/SocialIcons";
      at Input.error (E:\astro\hexw\node_modules\postcss\lib\input.js:106:16)
      at Parser.unknownWord (E:\astro\hexw\node_modules\postcss\lib\parser.js:593:22)
      at Parser.other (E:\astro\hexw\node_modules\postcss\lib\parser.js:435:12)
      at Parser.parse (E:\astro\hexw\node_modules\postcss\lib\parser.js:470:16)
      at parse (E:\astro\hexw\node_modules\postcss\lib\parse.js:11:12)
      at new LazyResult (E:\astro\hexw\node_modules\postcss\lib\lazy-result.js:133:16)
      at Processor.process (E:\astro\hexw\node_modules\postcss\lib\processor.js:53:14)
      at compileCSS (file:///E:/astro/hexw/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:32272:63)
      at async TransformContext.transform (file:///E:/astro/hexw/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:31583:56)
      at async Object.transform (file:///E:/astro/hexw/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:51139:30)
      at async loadAndTransform (file:///E:/astro/hexw/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:53894:29)
17:51:13 [200] /about/ 35ms

**Comment by emyia2001** [comment]
![image](https://github.com/hexWars/hexw/assets/75084293/93e05311-abd6-4278-9c47-c8489e8cf308)

**Comment by hexWars** [comment]
你删掉原来的项目重新下载试试，会不会是npm包的下载问题

**Comment by hexWars** [comment]
除此之外，我希望知道你的node版本

**Comment by emyia2001** [comment]
![image](https://github.com/hexWars/hexw/assets/75084293/a9a9241d-1e3c-4d71-a796-5c1e08bf3c41)

**Comment by hexWars** [comment]
很奇怪，我无法复现，你的node版本是没问题的，看起来是vite的问题？

我重新说明一下如何运行

1. 把项目下载下来
2. 在项目的目录里运行`npm install`，注意不能出现error
3. 执行`npm run dev`

我依旧觉得可能是你网络问题，包没有下载完全，如果还未能解决，请再联系我

**Comment by emyia2001** [comment]
![image](https://github.com/hexWars/hexw/assets/75084293/0607edbc-23fe-43e3-9278-d2dd31023fba)

**Comment by emyia2001** [comment]
重新clone了一次还是不行，但是可以直接部署到netlify上

**Comment by hexWars** [comment]
我明天再看看吧

**Comment by hexWars** [comment]
再试一次，重新clone然后运行npm install
